# Generated by Django 4.2 on 2026-06-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='exam_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='student_class',
            field=models.CharField(max_length=50),
        ),
    ]
