# Generated by Django 4.2 on 2026-07-05 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resultportal', '0002_alter_studentresult_exam_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_class', models.CharField(max_length=50)),
                ('exam_number', models.CharField(blank=True, default='', max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_marks', models.IntegerField(default=0)),
                ('time_started', models.DateTimeField()),
                ('time_completed', models.DateTimeField(blank=True, null=True)),
                ('answers', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TuitionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_class', models.CharField(max_length=50)),
                ('exam_number', models.CharField(blank=True, default='', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('term', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('online', 'Online Payment'), ('pos', 'POS')], max_length=20)),
                ('payment_date', models.DateField()),
                ('reference_number', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HolidayTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('task_type', models.CharField(choices=[('assignment', 'Assignment'), ('project', 'Project'), ('reading', 'Reading'), ('practice', 'Practice')], max_length=20)),
                ('student_class', models.CharField(max_length=50)),
                ('subject', models.CharField(blank=True, default='', max_length=100)),
                ('due_date', models.DateField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='holiday_tasks/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('student_class', models.CharField(max_length=50)),
                ('term', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank')], max_length=20)),
                ('option_a', models.CharField(blank=True, default='', max_length=200)),
                ('option_b', models.CharField(blank=True, default='', max_length=200)),
                ('option_c', models.CharField(blank=True, default='', max_length=200)),
                ('option_d', models.CharField(blank=True, default='', max_length=200)),
                ('correct_answer', models.CharField(max_length=200)),
                ('marks', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['subject', 'id'],
            },
        ),
    ]
