# Generated by Django 6.0.2 on 2026-08-04 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultportal', '0003_examattempt_tuitionpayment_holidaytask_examquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='First Goshen Gate School', max_length=200)),
                ('school_motto', models.CharField(blank=True, default="Nurturing Tomorrow's Leaders Today", max_length=200)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school/')),
                ('school_address', models.TextField(blank=True, default='')),
                ('school_phone', models.CharField(blank=True, default='', max_length=50)),
                ('school_email', models.EmailField(blank=True, default='', max_length=254)),
                ('current_session', models.CharField(default='2024/2025', max_length=20)),
                ('current_term', models.CharField(default='First Term', max_length=20)),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('full_name', models.CharField(max_length=200)),
                ('current_class', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=10)),
                ('parent_name', models.CharField(blank=True, default='', max_length=200)),
                ('parent_phone', models.CharField(blank=True, default='', max_length=20)),
                ('parent_email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='studentresult',
            name='ca1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='ca2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='exam_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='principal_remark',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='teacher_remark',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='PromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_class', models.CharField(max_length=50)),
                ('to_class', models.CharField(max_length=50)),
                ('session', models.CharField(blank=True, default='', max_length=20)),
                ('promoted_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='resultportal.student')),
            ],
        ),
    ]
